### ISSUE TITLE
Design Authors page

### ISSUE THREAD

**Issue by aref-asadi** [MedX-Media/MedX#5]
## Responsibility:
@aref-asadi

## Deadline:
19 Aug 2024

## Description:
We need to design an Authors page that lists all the authors with their profile pictures. The design should be straightforward and visually appealing, ensuring users can easily view and recognize the contributors.

## Authors Page Requirements:

1. Authors List:
- Display a list of all authors associated with MedX.
- Each author should be represented with their profile picture and name.

## Tasks:
- [x]  Design the layout of the Authors page to effectively showcase all authors. @aref-asadi 
- [x]  Review. @Sinusealpha

**Comment by aref-asadi** [comment]
V.1:
[Authors page design](https://github.com/MedX-Media/MedX/blob/development/design/MedX_website_design-Authors_page.jpg)

**Comment by Sinusealpha** [comment]
thank you @aref-asadi for your design. i think that's good enough, but i've some comments:

1. should we link the writer's social media accounts under their name? for example their LinkedIn or twitter. if you agree, i think that LinkedIn is much better in persian community. but if you do not agree, i think that we can think about our own profile for writers that can be much better than linkedin for introducing them. but the problem is that writers may want to brand themselves through their linkedin accounts and providing this feature for them may help.

2. i think we can change the text to "نویسندگان medx" (MedX's Writers) and that's better. using the word "contribution" is good, but "medx's writers" is much better to emphasize that they **belong** to medx!

there are no more points about this design and thank you again.

**Comment by aref-asadi** [comment]
> thank you @aref-asadi for your design. i think that's good enough, but i've some comments:
> 
> 1. should we link the writer's social media accounts under their name? for example their LinkedIn or twitter. if you agree, i think that LinkedIn is much better in persian community. but if you do not agree, i think that we can think about our own profile for writers that can be much better than linkedin for introducing them. but the problem is that writers may want to brand themselves through their linkedin accounts and providing this feature for them may help.
> 
> 2. i think we can change the text to "نویسندگان medx" (MedX's Writers) and that's better. using the word "contribution" is good, but "medx's writers" is much better to emphasize that they **belong** to medx!
> 
> there are no more points about this design and thank you again.

I believe that the more we can meet the needs of users within our own platform and minimize redirecting them outside, the better. Therefore, I disagree with placing external links on the authors' list page. However, in the future, we can consider adding a section for writers and users in their profiles where they can enter external links.

I agree with your second comment.

**Comment by Sinusealpha** [comment]
1- we are not obviously gonna play linkedin's role. so, like all other newsletters and media platforms, we need some external links. we also should provide some links for other types of content creators to lead people to their personal pages, in the Instagram, LinkedIn or even twitter.

**Comment by aref-asadi** [comment]
> 1- we are not obviously gonna play linkedin's role. so, like all other newsletters and media platforms, we need some external links. we also should provide some links for other types of content creators to lead people to their personal pages, in the Instagram, LinkedIn or even twitter. 
> 
> 

Yes, I agree, but not on the authors' list page. Instead, I think it would be better to include external links on the author’s personal page. This approach would at least encourage users to visit the author’s personal page.

**Comment by Sinusealpha** [comment]
you're completely right! thank you. do it.
